---
- name: Add apache sites configuration files.
  template:
    src: site.vhost.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ item.servername }}.vhost"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ apache_vhosts }}"
  notify: restart apache

- name: Add apache SSL sites configuration files.
  template:
    src: "ssl_site.vhost.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ item.servername }}.ssl.vhost"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ apache_vhosts_ssl }}"
  notify: restart apache

- name: Get current enabled Virtual Hosts.
  command: ls -1 {{ apache_conf_path }}/sites-enabled/
  register: apache_current_vhosts_enabled
  changed_when: false

- name: Define empty apache_vhosts_enabled variable
  set_fact:
    apache_vhosts_enabled: []

- name: Add default Virtual Host to apache_vhosts_enabled
  set_fact:
    apache_vhosts_enabled: "{{ apache_vhosts_enabled }} + ['{{ apache_default_vhost_filename | default('') }}']"
  when: apache_default_vhost_filename | default('') | length > 0 and not apache_remove_default_vhost

- name: Define Virtual Hosts counter
  set_fact:
    apache_vhosts_number: 0

- name: Add sites symlink in sites-enabled.
  include: create-vhost-config-file-symlink.yml
  vars:
    servername: "{{ item.servername }}"
    config_file: "{{ item.servername }}.vhost"
    create_symlink: item.enabled | default(True)
  with_items: "{{ apache_vhosts }}"

- name: Add SSL sites symlink in sites-enabled.
  include: create-vhost-config-file-symlink.yml
  vars:
    servername: "{{ item.servername }}"
    config_file: "{{ item.servername }}.ssl.vhost"
    create_symlink: item.enabled | default(True) and (apache_ignore_missing_ssl_certificate or item.certificate_file in apache_ssl_certificates)
  with_items: "{{ apache_vhosts_ssl }}"

- name: Delete old Virtual Hosts symlinks.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ item }}"
    state: absent
  when: item not in apache_vhosts_enabled
  with_items: "{{ apache_current_vhosts_enabled.stdout_lines }}"
  notify: restart apache
